# infrastructure/Lambda-da-ml-order-inicial-cl.yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaDaMlOrderInicialCl:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-da-ml-order-inicial-cl
      PackageType: Image
      Timeout: 60
      MemorySize: 2048
      Environment:
        Variables:
          STAGE: prod
    Metadata:
      Dockerfile: Dockerfile
      # ¡IMPORTANTE! Esto es CRÍTICO:
      # Opción A: Ruta relativa DESDE EL DIRECTORIO ACTUAL donde se ejecuta SAM
      DockerContext: ./lambdas/Lambda-da-ml-order-inicial-cl
      
      # Opción B: Ruta absoluta (más segura en CI/CD)
      # DockerContext: /home/runner/work/docker_lambda/docker_lambda/lambdas/Lambda-da-ml-order-inicial-cl
      
      DockerTag: latest
