name: Deploy Lambda

on:
  push:
    branches:
      - develop
      - qa
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::682033497219:role/githubrol
          role-session-name: darolesession
          aws-region: us-east-1

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy Lambdas
        run: |
          chmod +x scripts/deploy-from-title.sh
          
          # Leer lambdas desde templates/lambdas.yml
          while read LAMBDA_NAME; do
            if [ -n "$LAMBDA_NAME" ]; then
              echo "---"
              echo "Desplegando: $LAMBDA_NAME"
              scripts/deploy-from-title.sh "deploy: $LAMBDA_NAME"
            fi
          done < <(grep "name:" templates/lambdas.yml | cut -d':' -f2 | xargs)