name: Deploy Lambda by PR Title

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - develop
  #     - qa
  #     - prod
  push:
    branches:
      - develop
      - lambda_prueba_dockers
      - qa
      - prod

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    # if: >
    #   github.event.pull_request.merged == true &&
    #   startsWith(github.event.pull_request.title, 'deploy:')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::682033497219:role/githubrol
          role-session-name: darolesession
          aws-region: us-east-1

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
  
      # - name: Deploy Lambda Image
      #   run: |
      #     bash scripts/deploy-from-title.sh \
      #     "${{ github.event.pull_request.title }}"

      - name: Deploy Lambda Image
        run: |
          bash scripts/deploy-from-title.sh \
          "deploy:lambda-da-ml-order-inicial-cl"          